[package]

name = "rustfmt-nightly"
version = "2.0.0-rc.1"
authors = ["Nicholas Cameron <ncameron@mozilla.com>", "The Rustfmt developers"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/rust-lang/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "rustfmt-core/rustfmt-bin/build.rs"
categories = ["development-tools"]
edition = "2018"

[[bin]]
name = "rustfmt"
path = "rustfmt-core/rustfmt-bin/src/bin/main.rs"
test = false

[[bin]]
name = "cargo-fmt"
path = "rustfmt-core/rustfmt-bin/src/cargo-fmt/main.rs"
test = false

[[bin]]
name = "rustfmt-format-diff"
path = "rustfmt-core/rustfmt-bin/src/format-diff/main.rs"
test = false

[[bin]]
name = "git-rustfmt"
path = "rustfmt-core/rustfmt-bin/src/git-rustfmt/main.rs"
test = false

[features]
default = ["cargo-fmt", "rustfmt-format-diff"]
cargo-fmt = []
rustfmt-format-diff = []
generic-simd = ["rustfmt_lib/generic-simd"]

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
cargo_metadata = "0.9"
env_logger = "0.7"
getopts = "0.2"
log = "0.4"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
term = "0.6"
thiserror = "1.0"

rustfmt_lib = { path = "rustfmt-core/rustfmt-lib", version = "2.0.0-rc.1" }

[dev-dependencies]
lazy_static = "1.0"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"
